// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AuthPolicyState string

const (
	AuthPolicyState_Active   AuthPolicyState = "Active"
	AuthPolicyState_Inactive AuthPolicyState = "Inactive"
)

type AuthType string

const (
	AuthType_NONE    AuthType = "NONE"
	AuthType_AWS_IAM AuthType = "AWS_IAM"
)

type HealthCheckProtocolVersion string

const (
	HealthCheckProtocolVersion_HTTP1 HealthCheckProtocolVersion = "HTTP1"
	HealthCheckProtocolVersion_HTTP2 HealthCheckProtocolVersion = "HTTP2"
)

type IPAddressType string

const (
	IPAddressType_IPV4 IPAddressType = "IPV4"
	IPAddressType_IPV6 IPAddressType = "IPV6"
)

type LambdaEventStructureVersion string

const (
	LambdaEventStructureVersion_V1 LambdaEventStructureVersion = "V1"
	LambdaEventStructureVersion_V2 LambdaEventStructureVersion = "V2"
)

type ListenerProtocol string

const (
	ListenerProtocol_HTTP            ListenerProtocol = "HTTP"
	ListenerProtocol_HTTPS           ListenerProtocol = "HTTPS"
	ListenerProtocol_TLS_PASSTHROUGH ListenerProtocol = "TLS_PASSTHROUGH"
)

type PrivateDNSPreference string

const (
	PrivateDNSPreference_VERIFIED_DOMAINS_ONLY                  PrivateDNSPreference = "VERIFIED_DOMAINS_ONLY"
	PrivateDNSPreference_ALL_DOMAINS                            PrivateDNSPreference = "ALL_DOMAINS"
	PrivateDNSPreference_VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS PrivateDNSPreference = "VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS"
	PrivateDNSPreference_SPECIFIED_DOMAINS_ONLY                 PrivateDNSPreference = "SPECIFIED_DOMAINS_ONLY"
)

type ProtocolType string

const (
	ProtocolType_TCP ProtocolType = "TCP"
)

type ResourceConfigDNSResolution string

const (
	ResourceConfigDNSResolution_IN_VPC ResourceConfigDNSResolution = "IN_VPC"
	ResourceConfigDNSResolution_PUBLIC ResourceConfigDNSResolution = "PUBLIC"
)

type ResourceConfigurationIPAddressType string

const (
	ResourceConfigurationIPAddressType_IPV4      ResourceConfigurationIPAddressType = "IPV4"
	ResourceConfigurationIPAddressType_IPV6      ResourceConfigurationIPAddressType = "IPV6"
	ResourceConfigurationIPAddressType_DUALSTACK ResourceConfigurationIPAddressType = "DUALSTACK"
)

type ResourceConfigurationStatus string

const (
	ResourceConfigurationStatus_ACTIVE             ResourceConfigurationStatus = "ACTIVE"
	ResourceConfigurationStatus_CREATE_IN_PROGRESS ResourceConfigurationStatus = "CREATE_IN_PROGRESS"
	ResourceConfigurationStatus_UPDATE_IN_PROGRESS ResourceConfigurationStatus = "UPDATE_IN_PROGRESS"
	ResourceConfigurationStatus_DELETE_IN_PROGRESS ResourceConfigurationStatus = "DELETE_IN_PROGRESS"
	ResourceConfigurationStatus_CREATE_FAILED      ResourceConfigurationStatus = "CREATE_FAILED"
	ResourceConfigurationStatus_UPDATE_FAILED      ResourceConfigurationStatus = "UPDATE_FAILED"
	ResourceConfigurationStatus_DELETE_FAILED      ResourceConfigurationStatus = "DELETE_FAILED"
)

type ResourceConfigurationType string

const (
	ResourceConfigurationType_ARN    ResourceConfigurationType = "ARN"
	ResourceConfigurationType_CHILD  ResourceConfigurationType = "CHILD"
	ResourceConfigurationType_GROUP  ResourceConfigurationType = "GROUP"
	ResourceConfigurationType_SINGLE ResourceConfigurationType = "SINGLE"
)

type ResourceGatewayIPAddressType string

const (
	ResourceGatewayIPAddressType_IPV4      ResourceGatewayIPAddressType = "IPV4"
	ResourceGatewayIPAddressType_IPV6      ResourceGatewayIPAddressType = "IPV6"
	ResourceGatewayIPAddressType_DUALSTACK ResourceGatewayIPAddressType = "DUALSTACK"
)

type ResourceGatewayStatus string

const (
	ResourceGatewayStatus_ACTIVE             ResourceGatewayStatus = "ACTIVE"
	ResourceGatewayStatus_CREATE_IN_PROGRESS ResourceGatewayStatus = "CREATE_IN_PROGRESS"
	ResourceGatewayStatus_UPDATE_IN_PROGRESS ResourceGatewayStatus = "UPDATE_IN_PROGRESS"
	ResourceGatewayStatus_DELETE_IN_PROGRESS ResourceGatewayStatus = "DELETE_IN_PROGRESS"
	ResourceGatewayStatus_CREATE_FAILED      ResourceGatewayStatus = "CREATE_FAILED"
	ResourceGatewayStatus_UPDATE_FAILED      ResourceGatewayStatus = "UPDATE_FAILED"
	ResourceGatewayStatus_DELETE_FAILED      ResourceGatewayStatus = "DELETE_FAILED"
)

type ServiceNetworkLogType string

const (
	ServiceNetworkLogType_SERVICE  ServiceNetworkLogType = "SERVICE"
	ServiceNetworkLogType_RESOURCE ServiceNetworkLogType = "RESOURCE"
)

type ServiceNetworkResourceAssociationStatus string

const (
	ServiceNetworkResourceAssociationStatus_CREATE_IN_PROGRESS ServiceNetworkResourceAssociationStatus = "CREATE_IN_PROGRESS"
	ServiceNetworkResourceAssociationStatus_ACTIVE             ServiceNetworkResourceAssociationStatus = "ACTIVE"
	ServiceNetworkResourceAssociationStatus_PARTIAL            ServiceNetworkResourceAssociationStatus = "PARTIAL"
	ServiceNetworkResourceAssociationStatus_DELETE_IN_PROGRESS ServiceNetworkResourceAssociationStatus = "DELETE_IN_PROGRESS"
	ServiceNetworkResourceAssociationStatus_CREATE_FAILED      ServiceNetworkResourceAssociationStatus = "CREATE_FAILED"
	ServiceNetworkResourceAssociationStatus_DELETE_FAILED      ServiceNetworkResourceAssociationStatus = "DELETE_FAILED"
)

type ServiceNetworkServiceAssociationStatus string

const (
	ServiceNetworkServiceAssociationStatus_CREATE_IN_PROGRESS ServiceNetworkServiceAssociationStatus = "CREATE_IN_PROGRESS"
	ServiceNetworkServiceAssociationStatus_ACTIVE             ServiceNetworkServiceAssociationStatus = "ACTIVE"
	ServiceNetworkServiceAssociationStatus_DELETE_IN_PROGRESS ServiceNetworkServiceAssociationStatus = "DELETE_IN_PROGRESS"
	ServiceNetworkServiceAssociationStatus_CREATE_FAILED      ServiceNetworkServiceAssociationStatus = "CREATE_FAILED"
	ServiceNetworkServiceAssociationStatus_DELETE_FAILED      ServiceNetworkServiceAssociationStatus = "DELETE_FAILED"
)

type ServiceNetworkVPCAssociationStatus string

const (
	ServiceNetworkVPCAssociationStatus_CREATE_IN_PROGRESS ServiceNetworkVPCAssociationStatus = "CREATE_IN_PROGRESS"
	ServiceNetworkVPCAssociationStatus_ACTIVE             ServiceNetworkVPCAssociationStatus = "ACTIVE"
	ServiceNetworkVPCAssociationStatus_UPDATE_IN_PROGRESS ServiceNetworkVPCAssociationStatus = "UPDATE_IN_PROGRESS"
	ServiceNetworkVPCAssociationStatus_DELETE_IN_PROGRESS ServiceNetworkVPCAssociationStatus = "DELETE_IN_PROGRESS"
	ServiceNetworkVPCAssociationStatus_CREATE_FAILED      ServiceNetworkVPCAssociationStatus = "CREATE_FAILED"
	ServiceNetworkVPCAssociationStatus_DELETE_FAILED      ServiceNetworkVPCAssociationStatus = "DELETE_FAILED"
	ServiceNetworkVPCAssociationStatus_UPDATE_FAILED      ServiceNetworkVPCAssociationStatus = "UPDATE_FAILED"
)

type ServiceStatus string

const (
	ServiceStatus_ACTIVE             ServiceStatus = "ACTIVE"
	ServiceStatus_CREATE_IN_PROGRESS ServiceStatus = "CREATE_IN_PROGRESS"
	ServiceStatus_DELETE_IN_PROGRESS ServiceStatus = "DELETE_IN_PROGRESS"
	ServiceStatus_CREATE_FAILED      ServiceStatus = "CREATE_FAILED"
	ServiceStatus_DELETE_FAILED      ServiceStatus = "DELETE_FAILED"
)

type TargetGroupProtocol string

const (
	TargetGroupProtocol_HTTP  TargetGroupProtocol = "HTTP"
	TargetGroupProtocol_HTTPS TargetGroupProtocol = "HTTPS"
	TargetGroupProtocol_TCP   TargetGroupProtocol = "TCP"
)

type TargetGroupProtocolVersion string

const (
	TargetGroupProtocolVersion_HTTP1 TargetGroupProtocolVersion = "HTTP1"
	TargetGroupProtocolVersion_HTTP2 TargetGroupProtocolVersion = "HTTP2"
	TargetGroupProtocolVersion_GRPC  TargetGroupProtocolVersion = "GRPC"
)

type TargetGroupStatus string

const (
	TargetGroupStatus_CREATE_IN_PROGRESS TargetGroupStatus = "CREATE_IN_PROGRESS"
	TargetGroupStatus_ACTIVE             TargetGroupStatus = "ACTIVE"
	TargetGroupStatus_DELETE_IN_PROGRESS TargetGroupStatus = "DELETE_IN_PROGRESS"
	TargetGroupStatus_CREATE_FAILED      TargetGroupStatus = "CREATE_FAILED"
	TargetGroupStatus_DELETE_FAILED      TargetGroupStatus = "DELETE_FAILED"
)

type TargetGroupType string

const (
	TargetGroupType_IP       TargetGroupType = "IP"
	TargetGroupType_LAMBDA   TargetGroupType = "LAMBDA"
	TargetGroupType_INSTANCE TargetGroupType = "INSTANCE"
	TargetGroupType_ALB      TargetGroupType = "ALB"
)

type TargetStatus string

const (
	TargetStatus_DRAINING    TargetStatus = "DRAINING"
	TargetStatus_UNAVAILABLE TargetStatus = "UNAVAILABLE"
	TargetStatus_HEALTHY     TargetStatus = "HEALTHY"
	TargetStatus_UNHEALTHY   TargetStatus = "UNHEALTHY"
	TargetStatus_INITIAL     TargetStatus = "INITIAL"
	TargetStatus_UNUSED      TargetStatus = "UNUSED"
)

type ValidationExceptionReason string

const (
	ValidationExceptionReason_unknownOperation      ValidationExceptionReason = "unknownOperation"
	ValidationExceptionReason_cannotParse           ValidationExceptionReason = "cannotParse"
	ValidationExceptionReason_fieldValidationFailed ValidationExceptionReason = "fieldValidationFailed"
	ValidationExceptionReason_other                 ValidationExceptionReason = "other"
)

type VerificationStatus string

const (
	VerificationStatus_VERIFIED               VerificationStatus = "VERIFIED"
	VerificationStatus_PENDING                VerificationStatus = "PENDING"
	VerificationStatus_VERIFICATION_TIMED_OUT VerificationStatus = "VERIFICATION_TIMED_OUT"
)
